### ISSUE TITLE
Rename find to every and create Array compatible find 

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metasync#102]
`metasync.every` - find all that satisfies passed function
`metasync.find` - find first that satisfies passed function

**Comment by tshemsedinov** [comment]
Oh, we have #62 by @DzyubSpirit

**Comment by belochub** [comment]
We already have #92, with `every` implementation, and I don't think that #94 should be landed in its current state, because it modifies `find` to return array, when it must return just a value.
Instead, I can open a PR with changes proposed by me in https://github.com/metarhia/MetaSync/pull/94#issuecomment-297419385, which fixes `find` without wrapping its return value in array.

**Comment by belochub** [comment]
Another less sophisticated option is to fix #94, avoiding new PR creation.
@tshemsedinov, which one is better?

**Comment by nechaido** [comment]
@tshemsedinov 
>`metasync.every` - find all that satisfies passed function

I think it is behaviour of `filter`, `every` should return a true if every element in an array satisfies a condition. I propose we have this 4 functions:
* `filter` - return an array of all that satisfy condition
* `find` - returns a first element that satisfy condition
* `every` - returns true if every element in an array satisfies a condition
* `some` - returns true if al least one element in an array satisfies a condition

**Comment by DzyubSpirit** [comment]
This PR has been fully completed.
