### ISSUE TITLE
Change parallel and sequential contracts

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaSync#118]
Now `metasync.parallel(fns, done(result), data)`
In `v0.3` we need `metasync.parallel(fns, done(err, result), data)`

**Comment by tshemsedinov** [comment]
@DzyubSpirit see last commit to branch `v0.3`, I'v changed contracts but we need tests and examples. Also it may be incompatible with dependent modules of Metarhia, plz find where we use it and create issue before release `v0.3` to port that code. I'v also created a branch `v0.3` and a milestone `v0.3`

**Comment by DzyubSpirit** [comment]
@tshemsedinov The branch `v0.3` is even with master

**Comment by DzyubSpirit** [comment]
@tshemsedinov I've searched for `flow` and `composition` through all `metarhia` js repos code and have not found usages of these functions.
But I found typo using `metasync.parallel` in Impress [example](https://github.com/metarhia/Impress/blob/master/applications/example/www/examples/complex/getFsMongoRequest.json/get.js#L2).
Also there is incompatibility there. It seems like `metasync.parallel` is expected to store results to array because anonymous functions have not names. 
 P.S. Also I think that is evidence for `first implementations save results of asynchronous functions by 0,1.. keys`.

**Comment by DzyubSpirit** [comment]
Oh, I see, the branch `refactor-flow` has new commit.

**Comment by tshemsedinov** [comment]
@DzyubSpirit a single commit I mentioned yesterday

**Comment by DzyubSpirit** [comment]
@tshemsedinov
LGTM
