### ISSUE TITLE
Refactore toAsync function

### ISSUE THREAD

**Issue by DzyubSpirit** [metarhia/metasync#145]
`metasync.monad.toAsync` isn't understandable. It should be renamed.

Also maybe that implementing `splitArguments` function is better. Instead of:
```javascript
const af1 = api.metasync.monad.toAsync((args, callback) => {
  ...
});
```
use:
```javascript
const af1 = (...argsWithCallback) => {
  const [args, callback] = splitArguments(argsWithCallback);
  ....
};
```

**Comment by tshemsedinov** [comment]
We need better name for this function, `toAsync` doesn't describe it

**Comment by DzyubSpirit** [comment]
I think `withSpreadArguments` is good name

**Comment by tshemsedinov** [comment]
@DzyubSpirit we need examples how to work without `toAsync` and without `splitArguments` and include in those examples usage of `af1`.

**Comment by DzyubSpirit** [comment]
Instead can be written like that:
```javascript
const af1 = (...argsWithCallback) => {
  const len = argsWithCallback.length;
  const args = argsWithCallback.slice(0, len - 1);
  const callback = argsWithCallback[len - 1];
  ...
};
```

**Comment by tshemsedinov** [comment]
1. @DzyubSpirit We have `api.common.cb` to wrap callbacks. I think we can add `api.common.cbExtract(array)` to extract callback from and array. Or propose better name, because `splitArguments` is not good for that. Function `cbExtract` will modify array (remove callback from it) and return callback as a result (if have one).

2. Now we can write `api.common.spreadRight` instead of `api.metasync.monad.toAsync`. It will be even more abstract, it can spread convert any function of N arguments to function of M arguments. Usage:
```
const af1 = api.common.spreadRight((args, callback) => { });
const af2 = api.common.spreadRight((args, arg1, callback) => { });
```

**Comment by DzyubSpirit** [comment]
@tshemsedinov, I noticed that `api.common.cbExtract` does same as `pop` function in `Array.prototype`

**Comment by tshemsedinov** [comment]
@DzyubSpirit `cbExtract` also should check type and wrap it like `cb` does to avoid multiple calls.

**Comment by DzyubSpirit** [comment]
One point discussed in real life conversation is implementations may be not so good from theory side. 
The main purpose of this PR is building array functions on other asynchronous primitives. This purpose doesn't increase performance therefore I will close this PR
