### ISSUE TITLE
Unref timer for timeouts if flow, collector and queue

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metasync#205]
In [#90 ](https://github.com/metarhia/metasync/pull/90#discussion_r115124014) @aqrln proposed to call `unref` on timers. I closed that PR because we have different implementation (using prototypes instead of closures and  optimized for performance). But proposal is still actual for all async abstractions including `flow`, `collector` and `queue`. So @aqrln why do you think we need to detach timer from eventloop? Maybe it's better if timeout will hold process working until a bunch of async calls will return or timed out?

**Comment by aqrln** [comment]
@tshemsedinov IIRC, in that specific cases `unref()` was necessary to avoid keeping Node running longer than necessary if an operation had successfully completed before timeout.

**Comment by tshemsedinov** [comment]
@aqrln I see, but:
- `unref()` is not supported in browsers, we want to use metasynct in browser too, we need something like `if (typeof(timer) === 'object') timer.unref();` in this case;
- usually process for asynchronous I/O will be servers and clients or other long-term processes so termination is an edge case for such software and we can just call something like `flow.cancel()` or `collector.cancel()` before exit;
- single reason to use `unref()` is performance optimization. Do you know how it can affect performance?

**Comment by aqrln** [comment]
1. That's a fair point.
2. I don't see how can it be feasible to call cancel for all of the intermediate `flow` and `collector` objects that could be created virtually anywhere across the codebase upon exit.
3. No, it shouldn't affect performance at all.

**Comment by tshemsedinov** [comment]
@aqrln 
2. For servers and clients we need no `cancel` method because processes are long-term. But we need quick exit for "tools", where we use flow and collector for I/O chains and sometimes want to exit immediately before I/O chains finished. Even in "tools" it is a rare need. Maybe we need an examples and cases here.
3. Here they tells that it may affect: https://nodejs.org/dist/latest-v8.x/docs/api/timers.html#timers_timeout_unref

**Comment by aqrln** [comment]
2. The implication is that timeouts in `flow` and `collector` should not be set to anything longer than several seconds. I guess it might be okay if we document it, and note the reasons behind this restriction. Otherwise, as a user of the library, I would consider such a behavior to be a bug.

3. Thanks, I didn't know about that. Although, looking at the code: at the time when that note was written, calling `unref()` used to create a new `TimerWrap` (https://github.com/nodejs/node/blob/bdd1a740cb5029860a2eef20d8e9814f378d99c4/lib/timers.js#L257) unconditionally unless the timer had already been unrefed, but currently `Timeout.prototype.unref()` tries to reuse existing `TimerWrap` handles when possible (https://github.com/nodejs/node/blob/0d22858d67f5f8f7959a55ceca23adafe12827d5/lib/timers.js#L607). I don't possess enough knowledge about timers internal machinery to make any conclusions from that confidently though.
