### ISSUE TITLE
Add d.ts

### ISSUE THREAD

**Issue by IvanProdaiko94** [metarhia/metasync#375]
I suppose, there are users that likes this lib, but despite their desire, they face some obstacles while trying to use it with TypeScript.

**Comment by DzyubSpirit** [comment]
Can you say tell about obstacles? That's interesting :)

**Comment by IvanProdaiko94** [comment]
there is no types declarations, thus it is no good IDE auto addition.

**Comment by aqrln** [comment]
Providing the official typings bundled with the package is a lot of extra maintenance work: you can't just drop a .d.ts file and forget about it, because wrong typings are even worse than no typings, and they'll eventually become wrong quite soon. In order for those typings to be usable, they'd need to be updated in each commit that modifies the public API, and it just frankly doesn't make sense since we could just write the library itself in TypeScript to achieve the same thing with less friction. That said, we don't use TypeScript, and I don't think anyone of mainteners is willing to keep the typings up-to-date, not to mention that all of them, and not anyone, should have been if we were to do that.

If you (or anyone else) are willing to write and maintain the typings yourself, feel free to contribute them to DefinitelyTyped — that's exactly what it exists for. I'll go ahead and close this issue — if anyone else disagrees, then, again, feel free to reopen it or to leave a request to do so.
